### PR TITLE
sbt android plugin version bumped, multi dex enabled, android sdk ver…

### PR DESCRIPTION
**Pull request by pamu**
…sion bumped and sbt conf changed to latest

### CODE REVIEW

**Comment by javipacheco** [comment]
Hi @pamu and thanks for your contribution

If you remove `ReplacePropertiesGenerator` some samples in the project don't work

We use this task for replacing some strings in [this file](https://github.com/47deg/scala-android/blob/master/src/main/res/values/app_config.xml)

You should include `debug.properties` with your keys in order to the samples for Google Maps and OpenWeather work

The content of this file should be like

```
google.map.key=YOUR_KEY
openweather.api.key=YOUR_KEY
```

We know that this isn't the better option, we are looking for a better way to implement that. Suggestions are welcome

Are you using another way to load keys in your projects?

Thanks!

**Comment by pamu** [comment]
Sorry, I have ignored that completely. I will try to fix it.

But Can you help fix this error. @javipacheco 

```scala
def replaceValuesTask = Def.task[Seq[File]] {
    try {
      val dir: File = (binPath in Android).value
      val valuesFile: File =  new File(dir, "resources/res/values/values.xml")
      replaceContent(valuesFile)
      Seq(valuesFile)
    } catch {
      case e: Throwable =>
        println("An error occurred loading values.xml")
        throw e
    }
  }
```

The above task gives an compilation error saying it cannot find `binPath`

```
/ReplacePropertiesGenerator.scala:71: not found: value binPath
[error]       val dir: File = (binPath in Android).value
```

**Comment by javipacheco** [comment]
`binPath` was refactored in version `1.5`. I think that the next code should work

```scala
val dir: (File, File) = (collectResources in Android).value
val valuesFile: File =  new File(dir._2, "/values/values.xml")
```

Thanks!

**Comment by pamu** [comment]
done. Thanks a lot. @javipacheco

**Pull request merged**
